import { useEffect, useState } from "react";
import ChatInput from "./components/ChatInput";
import Header from "./components/Header";
import PromptCard from "./components/PromptCard";
import StatusBadge from "./components/StatusBadge";

interface Suggestion {
  id: string;
  title: string;
  icon: string;
}

interface MockResponse {
  greeting: string;
  suggestions: Suggestion[];
}

const fallbackSuggestions: Suggestion[] = [
  {
    id: "estimate",
    title: "Generate a detailed estimate template for",
    icon: "🧾"
  },
  {
    id: "follow-up",
    title: "Create a friendly follow-up email for a client",
    icon: "💌"
  },
  {
    id: "compare",
    title: "Compare two estimates",
    icon: "📊"
  },
  {
    id: "profile",
    title: "Create a sample client profile",
    icon: "👤"
  }
];

export default function App() {
  const [greeting, setGreeting] = useState("Hi! I am Lilly, your AI assistant.");
  const [suggestions, setSuggestions] = useState<Suggestion[]>(fallbackSuggestions);

  useEffect(() => {
    const fetchMock = async () => {
      if (typeof chrome === "undefined" || !chrome.runtime?.sendMessage) {
        return;
      }

      try {
        const response = await chrome.runtime.sendMessage({
          type: "mockApiRequest",
          payload: { topic: "sidebar" }
        });
        if (response?.ok && response.data) {
          const data = response.data as MockResponse;
          setGreeting(data.greeting);
          setSuggestions(data.suggestions);
        }
      } catch (error) {
        // Non-obvious: content pages can block runtime messaging when not loaded in extension context.
        console.warn("Mock API unavailable", error);
      }
    };

    fetchMock();
  }, []);

  return (
    <div className="flex h-screen flex-col bg-white text-slate-900">
      <div className="px-6 pt-6">
        <Header />
        <StatusBadge text="Connected" />
      </div>

      <div className="flex flex-1 flex-col gap-6 px-6 pt-4">
        <div className="text-center">
          <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-rose-50 shadow-soft">
            <div className="text-3xl">🌺</div>
          </div>
          <h1 className="mt-4 text-lg font-semibold text-slate-900">
            {greeting}
          </h1>
          <p className="mt-2 text-sm text-slate-500">
            I can help with estimates, follow-ups, comparisons, and onboarding.
          </p>
        </div>

        <div className="space-y-3">
          {suggestions.map((item) => (
            <PromptCard key={item.id} icon={item.icon} title={item.title} />
          ))}
        </div>
      </div>

      <div className="px-6 pb-4 pt-2">
        <ChatInput />
        <p className="mt-2 text-center text-xs text-slate-400">
          Messages are generated by AI. Some may be inaccurate or inappropriate.
        </p>
      </div>
    </div>
  );
}
